### ISSUE TITLE
Does not work on Glassfish 4.1 

### ISSUE THREAD

**Issue by alialagoz** [vaadin/cdi-tutorial#2]
Hi,
I tried to deploy the sample application to Glassfish 4.1 (running on Weld 2.2.2). (Changed the scopes of cdi-api and javax.annotation-api to provided). However when I tried to access the UI, I got the below exception.
  StandardWrapperValve[VaadinServlet]: Servlet.service() for servlet VaadinServlet threw exception
org.jboss.weld.context.ContextNotActiveException: WELD-001303: No active contexts for scope type com.vaadin.cdi.UIScoped

I created another project using vaadin-cdi v.1.0.2, observed the same problem.

**Comment by alialagoz** [comment]
I figured out the issue mentioned above. (I was using our internal Nexus repository where vaadin-cdi 1.0.2 deployed manually) After cleaning the m2 directory for cdi addon and disable nexus, I could access the UI. (It was because of manually created POM file) But now getting the below exception...

java.lang.RuntimeException: java.lang.IllegalStateException: Singleton not set for org.glassfish.main.core.kernel [229]
    at com.vaadin.cdi.tutorial.NavigationServiceImpl.onNavigationEvent(NavigationServiceImpl.java:38)
    at com.vaadin.cdi.tutorial.NavigationServiceImpl$Proxy$_$$_WeldSubclass.onNavigationEvent(Unknown Source)
    at com.vaadin.cdi.tutorial.NavigationLogDecorator.onNavigationEvent(NavigationLogDecorator.java:25)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.jboss.weld.annotated.runtime.InvokableAnnotatedMethod.invokeOnInstance(InvokableAnnotatedMethod.java:85)
    at org.jboss.weld.bean.proxy.DecoratorProxyMethodHandler.doInvoke(DecoratorProxyMethodHandler.java:78)
    at org.jboss.weld.bean.proxy.DecoratorProxyMethodHandler.doInvoke(DecoratorProxyMethodHandler.java:67)
    at org.jboss.weld.interceptor.util.proxy.TargetInstanceProxyMethodHandler.invoke(TargetInstanceProxyMethodHandler.java:33)
    at org.jboss.weld.bean.proxy.TargetBeanInstance.invoke(TargetBeanInstance.java:91)
    at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:100)
    at com.vaadin.cdi.tutorial.NavigationServiceImpl$Proxy$_$$_Weld$Proxy$.onNavigationEvent(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.jboss.weld.util.reflection.Reflections.invokeAndUnwrap(Reflections.java:414)
    at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:58)
    at com.vaadin.cdi.tutorial.NavigationServiceImpl$Proxy$_$$_WeldSubclass.onNavigationEvent(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.jboss.weld.injection.MethodInjectionPoint.invokeOnInstanceWithSpecialValue(MethodInjectionPoint.java:90)
    at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:271)
    at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:258)
    at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:237)
    at org.jboss.weld.event.ObserverNotifier.notifyObserver(ObserverNotifier.java:174)
    at org.jboss.weld.event.ObserverNotifier.notifyObserver(ObserverNotifier.java:170)
    at org.jboss.weld.event.TransactionalObserverNotifier.notifyObserver(TransactionalObserverNotifier.java:46)
    at org.jboss.weld.event.ObserverNotifier.notifyObservers(ObserverNotifier.java:124)
    at org.jboss.weld.event.EventImpl.fire(EventImpl.java:84)
    at com.vaadin.cdi.tutorial.LoginView.buttonClick(LoginView.java:69)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508)
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198)
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161)
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:979)
    at com.vaadin.ui.Button.fireClick(Button.java:380)
    at com.vaadin.ui.Button.click(Button.java:369)
    at com.vaadin.ui.Button$ClickShortcut.handleAction(Button.java:548)
    at com.vaadin.event.ActionManager.handleAction(ActionManager.java:238)
    at com.vaadin.event.ConnectorActionManager.handleAction(ConnectorActionManager.java:81)
    at com.vaadin.event.ActionManager.handleAction(ActionManager.java:233)
    at com.vaadin.event.ActionManager.handleActions(ActionManager.java:216)
    at com.vaadin.ui.UI.changeVariables(UI.java:361)
    at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:485)
    at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:301)
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:180)
    at com.vaadin.server.communication.PushHandler$3.run(PushHandler.java:174)
    at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:253)
    at com.vaadin.server.communication.PushHandler.access$200(PushHandler.java:56)
    at com.vaadin.server.communication.PushHandler$1.onRequest(PushHandler.java:76)
    at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:174)
    at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:95)
    at org.atmosphere.container.GlassFishServ30WebSocketSupport.service(GlassFishServ30WebSocketSupport.java:60)
    at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:1802)
    at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:432)
    at org.atmosphere.websocket.DefaultWebSocketProcessor$2.run(DefaultWebSocketProcessor.java:285)
    at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
    at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:280)
    at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:303)
    at org.atmosphere.container.GlassFishServ30WebSocketSupport$Grizzly2WebSocketApplication.onMessage(GlassFishServ30WebSocketSupport.java:157)
    at org.glassfish.grizzly.websockets.SimpleWebSocket.onMessage(SimpleWebSocket.java:163)
    at org.glassfish.grizzly.webs
